; GeoGreen - configuracion PlatformIO para el track Arduino UNO.
; PlatformIO descarga su propio compilador AVR: NO necesitas arduino-cli.

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
